version: "3"

services:
  bun:
    build:
      context: .
      dockerfile: bun.dockerfile
    working_dir: /usr/src/app
    volumes:
      - ../:/usr/src/app:delegated
      - node_modules:/usr/src/app/node_modules
    tty: true
volumes:
  node_modules:
